generate_content:
  fields:
    prompt:
      required: true
      selector:
        text:
          multiline: true
    image_filename:
      required: false
      selector:
        object:
    service_model:
      required: false
      selector:
        text:
          multiline: false